#!/bin/bash

docker run \
    --user $(id -u):$(id -g) \
    --rm \
    --volume "$PWD":/tmp/app \
    --workdir /tmp/app \
    maxsum:build /bin/bash -c 'source /tmp/venv/bin/activate && "$@"' _ "$@"

